language: android
android:
  components:
  - platform-tools
  - tools
  - android-28
  - build-tools-28.0.3
  - extra-android-support
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
jdk:
- oraclejdk8
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
script: "./gradlew :rxsmartlock:build :rxsmartlock:test :example:assembleDebug :example:testDebug"
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2"
after_success:
- "./deploy.sh"
env:
  global:
  - secure: gr31j0B3rHQOobGFFML8Pq613NnLc4RdR3GV0cDZfZbptgDfLavG89tPIkviYML66e+l1xaCYzWQivmLpmKs+prIKBLWnfb19lISwv1fBdJafbWoRb4WcXIo4lWcyaDxdnYsG3u+b7oadITCnMRGzAy/1KiniDvSC2EqUZShFf9iu96bcdx/Hbplm68Vw5BV2+77e00+IKkIR4NHZkOh8ZB6f7ytGedyF19LX3AyTNJzUwtBOo46pICdOufa5RS6nPP1iDNLWULEzF42j7vaP5Z8tU3nlp0zi2k/5l1U5Y22om9UFvOVt6x+xmoEPw0EyWpCp+BhHjKlbPLB5/qtYDfWsDdbiv3GU1zfBGx/Pkg+ivXavHZOdbczCzpjYWTeKRYmAqPiI26xYHDlBFKYcGSIhyzXIzMHWUqbETVbq7hrSXAShNLW2aGnLj8f8mEbexqYtoHFA6sq77yOj1xsUhkjQ5Mo2kGpR4+Ei7awMn7HkJIgGHF257YiDgxTyTOxDwx4BPT1FmHVS66d93yqfsq4jBQCSKIf2FJg4hYcIm5dxZhsR0akMxv9QQXBjRpTArM1RrPoGXRO+x0bLlWYMW1rX3T7T8NDEo0k0KjFJYBmwXiyzuDUBPvAjn8JNKekOYIjWYCqhnBJk+V1R5QE9FeGWVgodK30ClhY36yCsqM=
  - secure: RWXZoYSTdF1MYBxVJXmet20WATkG6zSuJlLoH7lB+DPXhPO6GQg0n4YSrNFsqMvtRQK1sFXIVVQMjFKhl4hrEcDNLNfn19RH/ICIUyh12veBCS9Boz3kUdyqnWZ5mSvGvDifDvRWR4E24rAAUmjKEkkpFxYzFZLupkvXJjAOi9focPXCeB7pmm0EEHDC4ExpuhZAPU5UI1YB7hgHW9hlCnYLdEYEeNuSQseh9RomnHWj0jCiBla9xdi6egoLN1ytScQfDDxDnv792frDdCal/LgCzGyaCeN9/XN7rJ0ZMFuhnRb7gofpKESm/eLtkNMjSEQnVLM2OIj9nlX8kTcVy63poAchfo7r060Pu2p3U5P9ZUTNik6NpbwGlFZ90ogM01x73tFFlqTtUV8+csIEoq6dAEQ1UjnuAIj9zaVgg22CnjEvsCIR7SaydZSxEGEdVs4PhgqHJH4+EgiOoM+HnXwja4gA7grY9D3s60ArYjMqEyYVgbwL3p90GYFU9m2fEqjs5qUfFgqUzBY7o+zN0+DjbXePVNIRqnpEJpoLdDEyrg/tx1VIyzCR9xB8OZLa1bHbpV5ZdkpGG92iYG4dwpxEbBGxDBcHi+M8FyaDfwHbQ+eh/mwpXIxxgy6yYl/R3+fKCfen5K83pQRX9lhvYTPwuo+E9ImBLt9S2qdbdzY=
  - secure: XU80M1635un/Ht9Bt/QM9XvLyT/szwF0kyv2QPQoKoQ/d1Vms4Ths2X6daU6o1+XNhBL7IU9WnfSBt4uvYqY1VJXrJ7I79CQVskxvxl0kWTQnlI5ySGZt4047889sHZrPW8zClj1cr/aHjP3T9t1ASjJBOpeLFAtfIdpR/3JyHyKeQvw/cYsnS03wk0BB12bFyJMZxeQXINhR3zhlJC7UZsS4Ocf4wBLXxIICnPRB9oR8uv71BOYqsIKtjKubodWEAv9ZXvA+KgP994GQHD6UzE36slym2Cpcz0nF6AV6cXt+fv/C+2fRucuAAejETsKsmxywlAQKL9ymhx8stxT/yMRMM5t/3/MMaOoYYzfZNJYbpKea3apvCGv3/Zg9m+XBYKvxTIQDsC0T2ydZRX0f9Xy4DoWWuNXAclWCWSQ/qXDftijKrKKDkr8q7p3jXerg3lDNgStGvVHGV8MwULM3viq9yxrft5MVVftLeJyaNkzqoPHnzsz1+w+nXf0lnLdk3XDkHlk9c0D3bnvTxj436EoT0x/eCpi+JyDlp0BpIZ5v/MhLwnobfUW6vylmKOCyri97qbw0zqucUTHNrYfi8AmXGG6X0S1m0eaYN2F0cqyOJhbDvDDbUHCdDZUmi7m6WcdAg5j5ESkdidMHzcyysy2WaH3gY5rY4+4JU0nZN0=
