version: 2.1

orbs:
  gradle-publish: freeletics/gradle-publish@1.0.4

executors:
  android:
    docker:
      - image: circleci/android:api-28
    working_directory: ~/rxsmartlock
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1536m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"


jobs:
  build:
    executor: android
    steps:
      - checkout
      - run: ./gradlew :rxsmartlock:build :rxsmartlock:test :example:assembleDebug :example:testDebug

workflows:

  build_and_deploy:
    jobs:
      - build
      - gradle-publish/publish_artifacts:
          executor: gradle-publish/circleci-android
          context: "android-maven-publish"
          requires:
            - build
          filters:
            branches:
              only:
                - master
